services:
  api-gateway:
    container_name: api-gateway
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file:
      - ./services/api-gateway/.env
    depends_on:
      - user-service
      - ambulance-service
      - blood-service
      - blood-bank-service
      - staff-service
      - booking-service
      - notification-service
      - review-service
      - ads-service 
      - role-service  
      - s3-service
      - bulmq-service
      - socketio-service
      - speciality-service
      - doctor-service
      - hospital-service
      - auth-service
    networks:
      - hosta-network

  user-service:
    container_name: user-service
    build: ./services/user-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file:
      - ./services/user-service/.env
    networks:
      - hosta-network

  ambulance-service:
    container_name: ambulance-service
    build: ./services/ambulance-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file:
      - ./services/ambulance-service/.env
    networks:
      - hosta-network
    depends_on:
      - role-service

  blood-service:
    container_name: blood-service
    build: ./services/blooddonor-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file:
      - ./services/blooddonor-service/.env
    networks:
      - hosta-network

  blood-bank-service:
    container_name: blood-bank-service
    build: ./services/blood-bank-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/blood-bank-service/.env
    networks:
      - hosta-network

#  pharmacy-service:
#    container_name: pharmacy-service
#    build: ./pharmacy-service
#    environment:
#      - NODE_OPTIONS=--dns-result-order=ipv4first
#    env_file: ./pharmacy-service/.env
#    networks:
#      - hosta-network

  staff-service:
    container_name: staff-service
    build: ./services/staff-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/staff-service/.env
    networks:
      - hosta-network
    depends_on:
      - hospital-service
      - role-service

  doctor-service:
    container_name: doctor-service
    build: ./services/doctor-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/doctor-service/.env
    networks:
      - hosta-network
    depends_on:
      - hospital-service
      - role-service

  speciality-service:
    container_name: speciality-service
    build: ./services/speciality-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/speciality-service/.env
    networks:
      - hosta-network 

  hospital-service:
    container_name: hospital-service
    build: ./services/hospital-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/hospital-service/.env
    networks:
      - hosta-network
    depends_on:
      - role-service

  booking-service:
    container_name: booking-service
    build: ./services/booking-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/booking-service/.env
    networks:
      - hosta-network
    depends_on:
      - role-service

#  medicine-reminder-service:
#    container_name: medicine-reminder-service
#    build: ./medicinremainder-service
#    environment:
#      - NODE_OPTIONS=--dns-result-order=ipv4first
#    env_file: ./medicinremainder-service/.env
#    networks:
#      - hosta-network

  notification-service:
    container_name: notification-service
    build: ./services/notification-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/notification-service/.env
    networks:
      - hosta-network

  review-service:
    container_name: review-service
    build: ./services/review-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/review-service/.env
    networks:
      - hosta-network

#  lab-service:
#    container_name: lab-service
#    build: ./lab-service
#    environment:
#      - NODE_OPTIONS=--dns-result-order=ipv4first
#    env_file: ./lab-service/.env
#    networks:
#      - hosta-network
#    depends_on:
#      - role-service

  ads-service:
    container_name: ads-service
    build: ./services/ads-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/ads-service/.env
    networks:
      - hosta-network
    depends_on:
      - role-service
  role-service:
    container_name: role-service
    build: ./services/role-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/role-service/.env
    networks:
      - hosta-network   

  s3-service:
    container_name: s3-service
    build: ./services/s3-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/s3-service/.env
    networks:
      - hosta-network  
  auth-service:
    container_name: auth-service
    build: ./services/auth-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/auth-service/.env
    networks:
      - hosta-network  

  bulmq-service:
    container_name: bulmq-service
    build: ./services/bulmq-service
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/bulmq-service/.env
    networks:
      - hosta-network

  socketio-service:
    container_name: socketio-service
    build: ./services/socketio-service
    ports:
      - "3019:3019"
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file: ./services/socketio-service/.env
    networks:
      - hosta-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - hosta-network

  restore-test-db:
    image: postgres:17-alpine
    container_name: restore-test-db
    restart: always
    environment:
      POSTGRES_USER: hosta_user
      POSTGRES_PASSWORD: "Hosta@123"
    ports:
      - "5432:5432"
    volumes:
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    networks:
      - hosta-network

networks:
  hosta-network:
    name: hosta-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1400"


