import { env } from "./env";

export const SERVICES = {
  USER_SERVICE: env.USER_SERVICE_URL,
  AMBULANCE_SERVICE: env.AMBULANCE_SERVICE_URL,
  BLOOD_SERVICE: env.BLOOD_SERVICE_URL,
  BLOOD_BANK_SERVICE: env.BLOOD_BANK_SERVICE_URL,
  // PHARMACY_SERVICE: env.PHARMACY_SERVICE_URL,
  STAFF_SERVICE: env.STAFF_SERVICE_URL,
  DOCTOR_SERVICE: env.DOCTOR_SERVICE_URL,
  SPECIALITY_SERVICE: env.SPECIALITY_SERVICE_URL, 
  HOSPITAL_SERVICE: env.HOSPITAL_SERVICE_URL,
  MEDICINREMINDER_SERVICE: env.MEDICINREMINDER_SERVICE_URL,
  BOOKING_SERVICE: env.BOOKING_SERVICE_URL,
  NOTIFICATION_SERVICE: env.NOTIFICATION_SERVICE_URL,
  REVIEW_SERVICE: env.REVIEW_SERVICE_URL,
  // LAB_SERVICE: env.LAB_SERVICE_URL,
  ADS_SERVICE: env.ADS_SERVICE_URL, 
  ROLE_SERVICE: env.ROLE_SERVICE_URL, 
  S3_SERVICE: env.S3_SERVICE_URL,
  BULMQ_SERVICE: env.BULMQ_SERVICE_URL,
  SOCKETIO_SERVICE: env.SOCKETIO_SERVICE_URL,
  AUTH_SERVICE: env.AUTH_SERVICE_URL,
};


if (!SERVICES.USER_SERVICE) {
  throw new Error("USER_SERVICE_URL not defined");
}

if (!SERVICES.AMBULANCE_SERVICE) {
  throw new Error("AMBULANCE_SERVICE_URL not defined");
}

if (!SERVICES.BLOOD_SERVICE) {
  throw new Error("BLOOD_SERVICE_URL not defined");
}

if (!SERVICES.BLOOD_BANK_SERVICE) {
  throw new Error("BLOOD_BANK_SERVICE_URL not defined");
}

// if (!SERVICES.PHARMACY_SERVICE) {
//   throw new Error("PHARMACY_SERVICE_URL not defined");
// }

if (!SERVICES.STAFF_SERVICE) {
  throw new Error("STAFF_SERVICE_URL not defined");
}



if (!SERVICES.DOCTOR_SERVICE) {
  throw new Error("DOCTOR_SERVICE_URL not defined");
}




if (!SERVICES.SPECIALITY_SERVICE) {
  throw new Error("SPECIALITY_SERVICE_URL not defined");
}

if (!SERVICES.HOSPITAL_SERVICE) {
  throw new Error("HOSPITAL_SERVICE_URL not defined");
}
if (!SERVICES.MEDICINREMINDER_SERVICE) {
  throw new Error("MEDICINREMINDER_SERVICE_URL not defined");
}


if (!SERVICES.BOOKING_SERVICE) {
  throw new Error("BOOKING_SERVICE_URL not defined");
}

if (!SERVICES.NOTIFICATION_SERVICE) {
  throw new Error("NOTIFICATION_SERVICE_URL not defined");
}

if (!SERVICES.REVIEW_SERVICE) {
  throw new Error("REVIEW_SERVICE_URL not defined");
}

// if (!SERVICES.LAB_SERVICE) {
//   throw new Error("LAB_SERVICE_URL not defined");
// }

if (  !SERVICES.ADS_SERVICE) {
  throw new Error("ADS_SERVICE_URL not defined");
}

if (!SERVICES.ROLE_SERVICE) {
  throw new Error("ROLE_SERVICE_URL not defined");
}

if (!SERVICES.S3_SERVICE) {
  throw new Error("S3_SERVICE_URL not defined");
}

if (!SERVICES.BULMQ_SERVICE) {
  throw new Error("BULMQ_SERVICE_URL not defined");
}

if (!SERVICES.SOCKETIO_SERVICE) {
  throw new Error("SOCKETIO_SERVICE_URL not defined");
}

if (!SERVICES.AUTH_SERVICE) {
  throw new Error("AUTH_SERVICE_URL not defined");
}